import mongoose from "mongoose";
const Schema = mongoose.Schema;

const ProductSchema = new Schema({

        name: {
            type: String, 
            required: true,
        },

        description: {
            type: String,
            required: true,
        },

        category: {
            type: String,
            ref: "Category",
            required: true,
        },

        brand: {
            type: String,
            required: false,
        },
        sizes: {
            type:[String], 
            enum: ["XS", "S", "M", "L", "XL", "XXL"],
            required: false,
        },
        dimensions: {
            type: [String], 
            required: false
        },

        colors: {
            type: String, 
            required: true,
        },
        user: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            ref: "User",
        },

        images: [
            {
                type: String,
                default: "https://mnc-img-01.sfo2.cdn.digitaloceanspaces.com/wp-content/uploads/sites/4/2017/08/serenade300x300-150x150@2x.jpg"
            }
        ],
//this is called referencing, we are using the id of the reviews and keeping it inside the array of reviews.
        reviews: [{
            type: mongoose.Schema.Types.ObjectId,
            ref: "Review",
        }],

        price: {
            type: Number,
            required: true,
        },

        totalQty: {
            type: Number, 
            required: true,
        },

        totalSold: {
            type: Number,
            required: true,
            default: 0,
        } 
    },
    { // we are going to use the autogenerated date a product was created
        timestamps: true,
        toJSON: {virtuals: true},
    },
);

const Product = mongoose.model("Product", ProductSchema);


export default Product;